### ISSUE TITLE
Create the setup.py to pip install

### ISSUE THREAD

**Issue by xweichu** [uccross/skyhookdm-pythonclient#2]

**Comment by xweichu** [comment]
Released the first version of skyhookdmpy which can be installed via 'pip install skyhookdmpy' command.  Issues need to be fixed when install the package in virtualenv.

**Comment by edeediong** [comment]
@xweichu , Can I work on this issue? I'm new to Open Source and I'd love to try this. But I'd need a bit more description though.

**Comment by xweichu** [comment]
thanks @edeediong , the issue was fixed. Need to close this issue.

**Comment by edeediong** [comment]
Oh that's totally fine🙂.
