### ISSUE TITLE
remove hard-coded values

### ISSUE THREAD

**Issue by ivotron** [uccross/skyhookdm-pythonclient#8]
there are multiple parts in the code where hard-coded values are used. For example: [here](https://github.com/uccross/skyhookdm-pythonclient/blob/master/skyhookdmpy/skyhook.py#L139), [here](https://github.com/uccross/skyhookdm-pythonclient/blob/master/skyhookdmpy/skyhook.py#L65), and [here](https://github.com/uccross/skyhookdm-pythonclient/blob/master/skyhookdmpy/skyhook.py#L14).  Using a config file (e.g. a skyhook.conf INI file) or exposing those variables through the API would improve the reusability of the code.

**Comment by xweichu** [comment]
All the mentioned hard coded values have been replaced. Safe to close this issue for now.
